platform :ios, '10.0'

target 'Homie' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'GooglePlacesAPI'
  pod 'SwiftyJSON'
  pod 'SRCountdownTimer'


  # Pods for Homie

end
